### ISSUE TITLE
Config cursors

### ISSUE THREAD

**Issue by sueloverso** [wiredtiger/wiredtiger#1133]
We have stubs for config cursors in `cur_config.c` and an entry in `session_api.c:__wt_open_cursor` but they have never been implemented.  The configuration of a config cursor should use the same naming to step into the complex config strings that log cursors use to step into the complex log records (which Michael and I decided on calling `step=boolean`).  Other considerations are how to specify what item or resource you want the config for, such as `config:connection` or `config:table:name`.

**Comment by agorrod** [comment]
bump. This functionality would be handy in the test code to validate reconfigure calls.

**Comment by agorrod** [comment]
I'll try to define what I think the API/interface will look like:

Supported URIs for creating config cursors via ```WT_SESSION::open_cursor```:

| URI | Result | Notes |
|---|---|---|
| config:connection | The content of the folded wiredtiger_open configuration string. ||
| config:session | The content of the current session configuration. ||
| config:transaction | The content of the current sessions transaction configuration. ||
| config:cursor | Iterates over each cursor open in this session. | TODO: Do we create a nested config string that contains a list of configs - one for each cursor in the session?|
| config:cursor:URI | Iterates over each cursor that has a prefix match on the URI | TODO: as for config:cursor |
| config:URI | Iterates over the config for the set of tables that prefix-match the URI. | Different to a metadata cursor, because that is designed to return the string as a blob of data (?) I'm inclined to leave this out - since I think the overlap with metadata cursors is confusing. |

Once a cursor is opened it is possible to iterate over all items in the cursor. Cursors (and possibly tables) could cause problems with search. If there are multiple entries that match the search, do we return the first one, then let users iterate across the others? i.e: Do we introduce duplicate support for this type of cursor.

It's not possible to enforce uniqueness for a cursor config search, since there can be multiple cursors open on the same URI. We could play games and pass in the cursor we want to get the configuration for to the dup parameter in the config case, but that's horrible.

**Comment by agorrod** [comment]
An example for cursor usage in pseudo code:

```
const char *cache_size_str;
long cache_size;
const char *home_dir;
cc = session->open_cursor(session, "config:connection", NULL, NULL);

/* Retrieve a number value */
cc->set_key(cc, "cache_size");
cc->search(cc);
cc->get_value(cc, &cache_size_str);
cache_size = atol(cache_size_str);
printf("cache size: %u\n", cache_size);

/*
 * Retrieve a string value. Home is a special case since it's not part of the
 * wiredtiger_open configuration but I suspect we want to expose it here.
 */
cc->set_key(cc, "home");
cc->search(cc);
cc->get_value(cc, &home_dir);
printf("home: %s\n", home_dir);

const char *next_key, *next_val;
cc->reset(cc);
while (cc->next(cc) == 0)
{
    cc->get_key(cc, &next_key);
    cc->get_value(cc, &next_val);
    printf("Got configuration pair %s:%s\n", next_key, next_val);
}
```

The output could be:

```
cache size: 104012894
home: WT_TEST

Got configuration pair async:(enabled=false,ops_max=1024,threads=2)
Got configuration pair buffer_alignment:-1
Got configuration pair cache_overhead:8
Got configuration pair cache_size:104012894
Got configuration pair checkpoint:(log_size=0,name=WiredTigerCheckpoint,wait=0)
etc
```

This raises a few questions. Should we support an additional input format:

```
session->open_cursor(session, "config:(enabled=false,ops_max=1024,threads=2)", NULL, NULL, &subcursor);
```

i.e: A way to pass in a configuration string that will be iterated over by the new cursor?

How do we deal with configuration settings that aren't strings? Is the value returned always a string, and it's up to the application to interpret it?

**Comment by sueloverso** [comment]
I think we might consider stepping into configuration settings similar to log cursors that step into each individual operation of a transaction commit record.  So complex configurations like lsm, log, async, checkpoint, etc. all can return the individual elements.  I think it will be difficult for a user to break apart a compound config string to get the one item they may be interested in like how many async threads there are.

**Comment by agorrod** [comment]
> similar to log cursors that step into each individual operation of a transaction commit record

I missed that part of the original issue description, sorry. Is there still a ```step=boolean``` configuration for log cursors? I couldn't see it in the documentation.

After reading the log cursor documentation page (http://source.wiredtiger.com/develop/cursor_log.html), the key has been carefully constructed so that each log record has a unique identifier and all log records consist of the same set of fields. That is each value has a well defined type so can be retrieved with a single get_value call. I believe the configuration cursors have an additional level of complexity that means such an approach isn't practical. Am I missing something? I think an equivalent to what we want here in the log cursor code would be having the ability to step into the ```logrec_value``` field and decoding it's structure.

Alternatively we also have the ```WT_CONFIG_PARSER``` functionality in ```wiredtiger.h``` - so it wouldn't be unreasonable to return the entire string and have applications interpret it that way. It makes for more complex application code and non-C API implementations.

**Comment by sueloverso** [comment]
The `step` setting for log cursors was removed after I found that there was never a reason not to step.  So that is what it does and there was no longer a need for the setting.  You're right that logging does have well-defined pieces that we can retrieve.   I'll toss this out for consideration.  What about something that returns the config "category" for the key and a `name=value` for the value?  For items that are not categories, it would be something like key: `cache_size` and value: `cache_size=104012894`.  For a category it would be key: `async` and value: `enabled=true`, then `next()` would be key: `async`, value: `threads=2`, and so on.
