### ISSUE TITLE
Improve wtstats.py ease of use

### ISSUE THREAD

**Issue by michaelcahill** [wiredtiger/wiredtiger#1365]
1. Allow a directory path, default to ".", and read all the `WiredTigerStat*` files in the directory

2. WiredTiger generates a lot of statistics, and by default, `wtstats.py` creates one graph including all of the statistics, which is hard to manage for humans and browsers.  Investigate whether newer versions of NVD3 offer anything to help, and if not, add a simple way to generate multiple graphs with fewer statistics in each one.

**Comment by keithbostic** [comment]
@michaelcahill, @monkey101 -- I'm closing WiredTiger issue #1365. Most of the topics in this issue are addressed by the separation of WiredTiger statistics into groups and the fabulous work @rueckstiess did on the wtstats tool. All of that work and the associated documentation has now been merged into the WiredTiger develop branch.

@michaelcahill noted [this page](https://aws.amazon.com/blogs/aws/highly-scalable-mysql-compat-rds-db-engine/) as an example of the kind of console that we should be able to build to make the WiredTiger statistics accessible over time, but I think that's likely to be something someone else takes on rather than the core server team.
