### ISSUE TITLE
Add WT_CURSOR::reconfigure

### ISSUE THREAD

**Issue by michaelcahill** [wiredtiger/wiredtiger#1381]
> currently we're using 'readonly' and 'overwrite' cursor attributes, so I have to cache 3 cursors. Probably reconfiguration will be more efficient.

**Comment by keithbostic** [comment]
Closed with the merge of #1467.

@dmitri-shubin, one thing I wanted to point out: the current WT_CURSOR.reconfigure implementation only supports the `append` and `overwrite` keywords, mostly because supporting `readonly` was significantly more difficult and we couldn't think of a use case. Please let us know if we missed a use case or this doesn't resolve your request for some other reason.

**Comment by dmitri-shubin** [comment]
Thanks!

I need to implement caching of WiredTiger cursors.
Please see my message -- https://groups.google.com/d/msg/wiredtiger-users/UvyvF9a9tTk/150ye5nmtEMJ

So after adding {{WT_CURSOR::reconfigure()}} I can cache only 2 cursors -- read-only and read-write.
