### ISSUE TITLE
Avoid collisions between WiredTiger Python wrapper naming and WiredTiger functions.

### ISSUE THREAD

**Issue by keithbostic** [wiredtiger/wiredtiger#1574]
@ddanderson, an issue for the build problem where internal WiredTiger names like `__wt_cursor_equals` collide with names generated by the Python SWIG wrapper.
```
wiredtiger_wrap.c:3442:16: error: conflicting types for ‘__wt_cursor_equals’
 SWIGINTERN int __wt_cursor_equals(struct __wt_cursor *self,WT_CURSOR *other){
                ^
In file included from /home/sue/wt.1571/build_posix/../src/include/wt_internal.h:318:0,
                 from wiredtiger_wrap.c:3010:
/home/sue/wt.1571/build_posix/../src/include/extern.h:283:12: note: previous declaration
of ‘__wt_cursor_equals’ was here
 extern int __wt_cursor_equals(WT_CURSOR *cursor, WT_CURSOR *other, int *equalp);
            ^
error: command 'gcc' failed with exit status 1
```
Would you please take a look and see if there's a fix to keep this from happening again?

If you want, feel free to revert 010059e when this is fixed.

**Comment by agorrod** [comment]
I agree a general solution would be better. When we have a general solution we should rename ```__wt_cursor_equal``` to ```__wt_cursor_equals``` so that it matches the API again.

**Comment by keithbostic** [comment]
@ddanderson notes:

I see, the concatenation that SWIG is using conflicts with a wiredtiger internal function.

I like the suggestion of a universal prefix. FTR, I think SWIG can do it: see  [5.4.7.2 Advanced renaming support](http://www.swig.org/Doc2.0/SWIG.html): `%rename("__wtwrap_%s") "";`

**Comment by sueloverso** [comment]
Does anyone know why only a few systems saw this error initially?  Was SWIG already generating unique names in some instances and not in others?

**Comment by ddanderson** [comment]
Turns out that the idea of using `%rename` globally doesn't work: renaming applies to top level class names and method names, creating a mapping from names in the C world to names in the Python world.  It does not address how SWIG generates wrapper names.  Generally, SWIG already prepends `_wrap_` or `_Java_` to these names. But in the case of `equals` and a few other functions, we needed to create our own special versions of these functions, intercepting the wrapper. SWIG doesn't prepend anything in these override cases (a possible SWIG bug/feature), and we're left with wrapper names with `<cname>_<methodname>` (like `"__wt_cursor_equals"`)

@agorrod had the only solution to the problem I could find, short of post processing the output, and the branch I just pushed generalizes that to the only cases that could conflict.  To make sure we got them all, there's a dist/s_lang script to check for potential conflicts: SWIG generated names that don't start with `_wrap_`, or don't have double underscore, or have `_python_` in them.

@agorrod, #1588 is ready to go, can you review?

**Comment by ddanderson** [comment]
@sueloverso, I don't understand why this happened on some machines and not others.  I've wondered if #1577 is involved (running the test suite you'd pick up a previously installed version of the python wrapper), but I think that would give different symptoms than you saw.

**Comment by keithbostic** [comment]
Close with the merge of #1588.
