### ISSUE TITLE
Test recovery after a crash

### ISSUE THREAD

**Issue by agorrod** [wiredtiger/wiredtiger#1622]
We don't currently have tests that check for bugs in our file ID allocation code.

The particular steps we are interested in recreating are:

* Create a table (t1).
* Do a clean restart.
* Create another table (t2).
* Insert data into t2.
* Make recovery run.

If we aren't tracking file IDs properly, it's possible that we'd end up apply the log records for t2 to table t1.

This sequence should be possible using our Python test suite, but would be different to existing test cases.

**Comment by michaelcahill** [comment]
Note that we could do this by taking a copy of the database directory after inserting data into t2 and opening the copy: we don't have to kill anything...

**Comment by michaelcahill** [comment]
We can easily test if something has gone wrong with `wt list -v`: if we see two "file:" URIs with the same "id=X", we have a bug.

**Comment by sueloverso** [comment]
@michaelcahill I've been looking at this today and I'm missing a key understanding of what your fix in df96addef5f3 changed and how to make this test fail in pre-fix code but succeed now.  The description above and in that change must be too simplistic to describe a key detail of the problem.

The crux of the problem based on the description is really that after running recovery after the clean shutdown, t2 somehow gets assigned the same fileid as t1.  It is only when there is another crash that it is noticed.  But as you said, after t2 is created we could just look at the `id=` fields for both tables in the metadata.

If I look at the master branch code, changeset 283e288588c2e8b, and taking the above description, here's what I see going on in the system.
* start with a fresh/empty system.
* create t1. It gets assigned fileid 1.
* t1 gets written into the metadata file with `id=1`
* clean shutdown
* reopen/run recovery:
  * after `__recovery_setup_file` on metadata, `r->nfiles` is 1.
  * essentially skip metadata recovery since checkpoint is at the end.
  * Call `__recovery_file_scan` to walk the metadata and see t1.  Call `__recovery_setup_file`.
  * t1's `id` is 1.  Set `r->nfiles = fileid + 1` (2)
  * at end of `__recovery_file_scan` set `r->max_fileid` to `r->nfiles` (2)
  * essentially skip normal recovery pass since checkpoint is at the end.
  * set `conn->next_file_id` to `r->max_fileid` (2).
* create t2:
  * In `__create_file` write t2's metadata and write `id=3` from `++S2C(session)->next_file_id`.
  * insert some data into t2

I've tried dropping tables, creating more or new ones, inserting data into t1, not inserting anything into t1, etc.  I don't see how we were not setting the correct minimum fileid from the metadata before your change.  With the test written as described above, the right things are happening on both code versions.

Since forward analysis didn't work, going backward, in order for t2 to get `id=1`, recovery must have initialized `conn->next_file_id` to zero or skipped it entirely.  I'm not seeing the path of how this problem came about.  Note this description is only dealing with reading the metadata file and initializing things.  The log itself is not involved here.  So, in fact, your change cannot affect this because your change is only on the log-recovery-callback path.

What am I missing?

**Comment by sueloverso** [comment]
Ok.  I understand this now.  The code in master is correct and does not have the bug.  The problem was introduced with changeset d718ad6d09f4933c.  I'll take care of the pull request.
