### ISSUE TITLE
cfg allocations

### ISSUE THREAD

**Issue by keithbostic** [wiredtiger/wiredtiger#1672]
There's a bug pointed out in [Coverity 44261](https://coverity.mongodb.com/reports.htm#v12392/p10001/fileInstanceId=6667452&defectInstanceId=2702160&mergedDefectId=47823):

schema_truncate.c allocates `const char *cfg[2]`
calls __wt_open_cursor
calls __wt_clsm_open
calls __wt_config_gets_def
which looks in `cfg[2]`.

There are other places in the system where we allocate fixed-size `cfg` arrays that have only two elements -- do they have the same problem, maybe, will they ever have the same problem, I'm a lot less confident.

Maybe we need a new type which is a config-array type, that is known to have more slots than we'll need?

@michaelcahill, you know the config code best, any thoughts?

**Comment by GeertBosch** [comment]
I'm looking at SERVER-17254, where a 10 seconds multithreaded insertion load on a replset, followed by dropping all collections, while having 20 clients reading the oplog, gets in a state where the insertion rate drops from 100K ops/sec down to about 250 inserts/second and does not recover for 10 minutes even after the oplog readers are terminated. Many threads are spinning on a lock at session_api.c:530 while the thread holding the lock spends a lot of time parsing config strings.

**Comment by michaelcahill** [comment]
I don't think there's a real bug here: `__wt_config_gets_def` looks in `cfg[1]`, and only if it is non-NULL does it look at `cfg[2]`.  In all cases I can see, the `cfg` array is correctly NULL-terminated.

I guess I don't really object to always allocating a minimum array size of 3, but I don't think that will actually make our code more robust.  What would help is carrying the length around with the array and asserting that (a) any new entries are added before the end, and (b) it is always NULL-terminated.

**Comment by keithbostic** [comment]
Fair enough, I didn't notice that -- I'll close this one for now, I can't off-hand think of any way to make this better that isn't a ton of work.
