### ISSUE TITLE
broken search in index with custom collator

### ISSUE THREAD

**Issue by dmitri-shubin** [wiredtiger/wiredtiger#1714]
Hi!

I implemented custom index collator as described in [Custom Collators for Indices] (http://source.wiredtiger.com/develop/custom_collators.html)
But looks like I need to consider the case when search on secondary key is performed and thus I have no primary key for the first key given to ```WT_COLLATOR::compare()```
Could you please advise how I can do that?

Test that demonstrates the problem:
```
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <wiredtiger.h>

#define WT_HOME "index_collator.db"

#define WT_CALL(call) \
    do { \
        const int __rc = call; \
        if (__rc != 0) { \
            fprintf(stderr, # call " at (%s:%d) failed: %s [%d]\n", __FILE__, __LINE__, wiredtiger_strerror(__rc), __rc); \
            exit(EXIT_FAILURE); \
        } \
    } while (0)

static int
compare_int(int a, int b)
{
    return (a < b ? -1 : (a > b ? 1 : 0));
}

static int
index_compare(WT_COLLATOR *collator, WT_SESSION *session,
              const WT_ITEM *key1, const WT_ITEM *key2, int *cmp)
{
    int rc;
    int ikey1 = 12345, pkey1 = 54321, ikey2 = 67890, pkey2 = 9876;

    WT_CALL(wiredtiger_struct_unpack(session, key1->data, key1->size, "ii", &ikey1, &pkey1));
    WT_CALL(wiredtiger_struct_unpack(session, key2->data, key2->size, "ii", &ikey2, &pkey2));

    printf("index_compare: ikey1 = %d, pkey1 = %d, ikey2 = %d, pkey2 = %d\n", ikey1, pkey1, ikey2, pkey2);

    if ((*cmp = compare_int(ikey1, ikey2)) != 0)
        return 0;

    *cmp = compare_int(pkey1, pkey2);
    return 0;
}

static WT_COLLATOR index_coll = { index_compare, NULL, NULL };

int
main(void)
{
    WT_CONNECTION *conn;
    WT_SESSION *session;
    WT_CURSOR *cursor;

    assert(system("rm -rf \"" WT_HOME "\" && mkdir \"" WT_HOME "\"") == 0);

    WT_CALL(wiredtiger_open(WT_HOME, NULL, "create", &conn));
    WT_CALL(conn->open_session(conn, NULL, NULL, &session));

    WT_CALL(conn->add_collator(conn, "index_coll", &index_coll, NULL));

    WT_CALL(session->create(session, "table:main", "key_format=i,value_format=i,columns=(k,v)"));
    WT_CALL(session->create(session, "index:main:index", "columns=(v),collator=index_coll"));

    WT_CALL(session->open_cursor(session, "table:main", NULL, NULL, &cursor));
    cursor->set_key(cursor, 13);
    cursor->set_value(cursor, 17);
    WT_CALL(cursor->insert(cursor));
    WT_CALL(cursor->close(cursor));

    WT_CALL(session->open_cursor(session, "index:main:index", NULL, NULL, &cursor));

    while (cursor->next(cursor) == 0) {
        int ikey, val;
        WT_CALL(cursor->get_key(cursor, &ikey));
        WT_CALL(cursor->get_value(cursor, &val));
        printf("ikey = %d, value = %d\n", ikey, val);
    }

    cursor->set_key(cursor, 17);
    WT_CALL(cursor->search(cursor));

    WT_CALL(cursor->close(cursor));

    WT_CALL(conn->close(conn, NULL));

    return 0;
}
```

Running it I can get:
```
$ ./index_collator
ikey = 17, value = 17
wiredtiger_struct_unpack(session, key1->data, key1->size, "ii", &ikey1, &pkey1) at (index_collator.c:32) failed: Invalid argument [22]
$ ./index_collator
ikey = 17, value = 17
index_compare: ikey1 = 17, pkey1 = 2962, ikey2 = 17, pkey2 = 13
cursor->search(cursor) at (index_collator.c:79) failed: WT_NOTFOUND: item not found [-31803]
$ ./index_collator
ikey = 17, value = 17
index_compare: ikey1 = 17, pkey1 = -21, ikey2 = 17, pkey2 = 13
index_compare: ikey1 = 17, pkey1 = -21, ikey2 = 17, pkey2 = 13
index_compare: ikey1 = 17, pkey1 = -21, ikey2 = 17, pkey2 = 13
```

Thanks!

**Comment by ddanderson** [comment]
Hello @dmitri-shubin,

The call to `wiredtiger_struct_unpack` must match the call that creates the index. The problem in the program you summitted is that `"columns=(v)"` is one item, and does not match `"ii"`. If your collator needs more information from other fields, those fields need to be declared in the index as well.

Since your program uses variables `pkeyN`, I'm assuming you want to look at the primary key as a tie breaker? To be able to examine the primary key in your collator, the index would have to be declared with `"columns=(v,k)"`. Then you can unpack with `"ii"` and you'll get the expected result. Note that declaring the index to include the primary key doesn't cost anything extra in the index file. WiredTiger knows that the primary key is already available, so an index table with `columns=(v)` and one with `columns=(v,k)` have exactly the same physical contents.

I've modified your program `main` to show this (the rest of your program is identical):
```
int
main(void)
{
    WT_CONNECTION *conn;
    WT_SESSION *session;
    WT_CURSOR *cursor;
    int exact, ikey, pkey, val;

    assert(system("rm -rf \"" WT_HOME "\" && mkdir \"" WT_HOME "\"") == 0);

    WT_CALL(wiredtiger_open(WT_HOME, NULL, "create", &conn));
    WT_CALL(conn->open_session(conn, NULL, NULL, &session));

    WT_CALL(conn->add_collator(conn, "index_coll", &index_coll, NULL));

    WT_CALL(session->create(session, "table:main", "key_format=i,value_format=i,columns=(k,v)"));
    WT_CALL(session->create(session, "index:main:index", "columns=(v,k),collator=index_coll"));

    WT_CALL(session->open_cursor(session, "table:main", NULL, NULL, &cursor));
    cursor->set_key(cursor, 13);
    cursor->set_value(cursor, 17);
    WT_CALL(cursor->insert(cursor));
    WT_CALL(cursor->close(cursor));

    WT_CALL(session->open_cursor(session, "index:main:index", NULL, NULL, &cursor));

    while (cursor->next(cursor) == 0) {
        WT_CALL(cursor->get_key(cursor, &ikey, &pkey));
        WT_CALL(cursor->get_value(cursor, &val));
        printf("ikey = %d, pkey = %d, value = %d\n", ikey, pkey, val);
    }

    cursor->set_key(cursor, 17, 0);
    WT_CALL(cursor->search_near(cursor, &exact));
    /*TODO: more logic needed to walk through multiple values returned */
    WT_CALL(cursor->get_key(cursor, &ikey, &pkey));
    WT_CALL(cursor->get_value(cursor, &val));
    printf("exact = %d, ikey = %d, pkey = %d, value = %d\n",
   	exact, ikey, pkey, val);

    WT_CALL(cursor->close(cursor));

    WT_CALL(conn->close(conn, NULL));

    return 0;
}
```

**Comment by dmitri-shubin** [comment]
Hi @ddanderson 

Thank you for reply!

> Since your program uses variables pkeyN, I'm assuming you want to look at the primary key as a tie > breaker?

I thought I have to according to documentation -- [Custom Collators for Indices] (http://source.wiredtiger.com/develop/custom_collators.html#custom_collators_indices):

>A collator must give an unambiguous ordering to records in the index, so it must use the primary key columns as well as the index columns when comparing two index records.

>What this means in practice is that if the table has key_format=r and the index is on a string column, then the index cursor will have key_format=S, but the actual keys stored in the index will have key_format=Sr (with the primary key appended).

>Collators usually call wiredtiger_struct_unpack with the appropriate format to split the index key into fields that are used for the comparison. 

Did I misunderstand it?

The changes you suggested will work, but it seems a bit unnatural that I should change application code (changing ```cursor->set_key(cursor, 17)``` to ```cursor->set_key(cursor, 17, 0)```) depending on collator used for the index.

Thanks!

**Comment by ddanderson** [comment]
Hi @dmitri-shubin, 
> The changes you suggested will work, but it seems a bit unnatural that I should change application code (changing `cursor->set_key(cursor, 17)` to `cursor->set_key(cursor, 17, 0)`) depending on collator used for the index.

Whether or not you are using indexes or collators, the `set_key()` call args must match the `columns=` for the thing you opened.

I think the documentation may be misleading or perhaps wrong. 
> A collator must give an unambiguous ordering to records in the index, so it must use the primary key columns as well as the index columns when comparing two index records.

It seems there may be some cases that the collator can give an unambiguous ordering to records without accessing the primary key. For example, for an index on a unique field (i.e. no duplicates for that field in the index).  Or perhaps some set of values included in the index keys would make it unique. So while it's true that including the primary key will make it unique, I don't think we require you to do so as long as you meet the ordering requirement.

I think the doc is trying to both specify the collator's job but is also describing what happens without a collator (since WT always includes the primary key). I'll check with the rest of the team about this point and try to clarify the doc.

I think if in your case you you have duplicates for field `v`, then you need something else to make it unique, the only thing left is the primary key.

Thanks!

**Comment by ddanderson** [comment]
@michaelcahill, about this doc:
```
A collator must give an unambiguous ordering to records in the index so it
must use the primary key columns as well as the index columns when
comparing two index records.

What this means in practice is that if the table has \c key_format=r and
the index is on a string column, then the index cursor will have
\c key_format=S, but the actual keys stored in the index will have
\c key_format=Sr (with the primary key appended).
```
What @dmitri-shubin is seeing is different.  If the index is declared as `key_columns=(somestring)`, then internally we store the index as `Sr` but the collator only has access via unpack to the first item using a `"S"` argument.  If we believe the doc, then unpack should have access to the 'hidden' primary key at the end, and we should fix unpack so it will correctly find both items with `"Sr"`. My first instinct is that the doc is wrong -- you only get access to the primary key via if you declare it in the index.  If that's true, then why should we even store a hidden primary for an index that is not declared with the primary key when it lists custom collator? I suppose if a collator doesn't live up to its contract (of unambiguously differentiating records) then it's helpful to have unique entries, but is there something else I'm missing?

**Comment by michaelcahill** [comment]
@ddanderson, we store the primary key in the index because the primary key is needed to do lookups in the primary.  We append it to the index key so that the physical key in the index is unique (since WiredTiger doesn't have support for multiple records with the same key).

I agree that the docs are not clear on this issue and I will update them.

The full physical index key (including the primary key) is available to the collator, but when an application does a `WT_CURSOR::search` or `WT_CURSOR::search_near`, the search key in the cursor doesn't include the primary key, so the collator has to cope with both possibilities.  Here is some code to do that, but note that it relies on a bug fix that I just put into the `develop` branch:

```c
static int
index_compare(WT_COLLATOR *collator, WT_SESSION *session,
              const WT_ITEM *key1, const WT_ITEM *key2, int *cmp)
{
    WT_PACK_STREAM *s1, *s2;
    int64_t ikey1 = 12345, pkey1 = 54321, ikey2 = 67890, pkey2 = 9876;
    int rc1, rc2;

    /*
     * Unpack the key columns.
     *
     * They must all have the index key (the first "i"), and they may also have
     * the primary key (the second "i").  The primary key is missing during a
     * search, when the application-supplied lookup key doesn't come with the
     * primary key.
     */
    WT_CALL(wiredtiger_unpack_start(session, "ii", key1->data, key1->size, &s1));
    WT_CALL(wiredtiger_unpack_int(s1, &ikey1));
    WT_CALL(wiredtiger_unpack_start(session, "ii", key2->data, key2->size, &s2));
    WT_CALL(wiredtiger_unpack_int(s2, &ikey2));

    printf("index_compare: ikey1 = %d, ikey2 = %d\n", (int)ikey1, (int)ikey2);

    if ((*cmp = compare_int((int)ikey1, (int)ikey2)) == 0) {
	/* We found a matching index key, now compare primary keys. */
        if (wiredtiger_unpack_int(s1, &pkey1) != 0)
            *cmp = -1;
	else if (wiredtiger_unpack_int(s2, &pkey2) != 0)
            *cmp = 1;
	else
            *cmp = compare_int(pkey1, pkey2);
    }

    WT_CALL(wiredtiger_pack_close(s1, NULL));
    WT_CALL(wiredtiger_pack_close(s2, NULL));
    return 0;
}
```

@dmitri-shubin, I hope this makes sense.  Please let us know if you have further questions about this.

**Comment by dmitri-shubin** [comment]
Hi @michaelcahill,

Thank you, that makes perfect sense for me.

And after your fix I assume ```wiredtiger_struct_unpack()``` from my first program will also return error when there is no primary key, right?

**Comment by michaelcahill** [comment]
Hi @dmitri-shubin: yes, the original call to `wiredtiger_struct_unpack` should now return an error when there is no primary key.

**Comment by ddanderson** [comment]
Closing, all the needed work here is done.
