### ISSUE TITLE
Make directory sync operation optional

### ISSUE THREAD

**Issue by michaelcahill** [wiredtiger/wiredtiger#1802]
Investigate the performance impact of `__wt_directory_sync` in workloads that do a significant number of those operations (e.g., insert workload with small log files, or an LSM workload with small chunks).

If the directory sync is expensive, consider making it optional (presumably with a `wiredtiger_open` config `directory_sync=true/false`).  The standard says that some filesystems may require it for durability, but in practice the most commonly used filesystems don't.

**Comment by keithbostic** [comment]
@michaelcahill: This scares me some because from my reading there's widespread disagreement as to which filesystems need a directory sync (and my reading of POSIX makes me think the filesystem could change its behavior any time it wanted without documenting the change). Instead of making the sync optional, could we cache the file handles? That could make the calls significantly less expensive since we won't have the open/close pair on each call.

**Comment by sueloverso** [comment]
We definitely can and should cache the directory handles.  We already cache the directory handle for the log files for just that reason.  The logging code sets a flag to flush the directory, if needed, anytime it is doing a synchronous log operation.

How many directories do we have that need this besides the database home and logging?  The only other one I can think of offhand is statistics logging which does not require directory sync for correctness.  So we're talking one additional file handle for the database home.

**Comment by keithbostic** [comment]
The one I'm most concerned about is the database home (the turtle file gets updated regularly, for example). Are there any files that aren't always in the database home directory?

**Comment by sueloverso** [comment]
> Are there any files that aren't always in the database home directory?

Only logging, which already does its own thing.  Once this is fleshed out, the log code should be evaluated to see if it can use the same code path.  I will note that logging only syncs the directory on a synchronous operation.  It does not do so on every log file switch.  Although the header is fsync'ed to the new log file (or a pre-allocated one), until the caller asks for a sync, the rename to the log file name is not sync'ed to the directory.

**Comment by bdlucas1** [comment]
In MongoDB if you specify --directoryPerDB or
--wiredTigerDirectoryForIndexes then collection and index tables end up in
subdirectories of the database home directory. I don't expect that updates
to those directories are very frequent however - only when collections and
indexes are added or removed. Still there are scenarios where a large
number of collections or indexes get created in a short time, and anything
that can be done to reduce the overhead of that is good. ISTR there being a
ticket or two around the performance of those scenarios.
Bruce

**Comment by sueloverso** [comment]
> Still there are scenarios where a large number of collections or indexes get created in a short time, and anything that can be done to reduce the overhead of that is good. ISTR there being a ticket or two around the performance of those scenarios.

FTR, I think you're thinking of:
#1439 / SERVER-16353 and #1634 / SERVER-17078.  Both of those were hampered by long list traversals that were fixed or improved with hash buckets.  However, #1439 deals with creation of many files and I would expect that sync'ing the directory on every creation will definitely have an impact.  Are those the ones you're thinking of?

Clearly we'd need to cache the file handle because as Keith points out, the impact of open/sync/close would be even greater.  But we still need to be smart about the directory sync.  We don't want to sync multiple times (i.e. syncing the directory when updating the turtle file and syncing it again when creating the file and possibly syncing it again if we change log files and it is a synchronous operation and logs happen to be in that directory too).

**Comment by bdlucas1** [comment]
Yes, I think those are the tickets. Good to hear it's been improved.

General statement: whether you need to sync the directory multiple times
depends on the ordering constraints on the required visibility of the files
to ensure consistency, e.g. in case of a crash. Applying that true
statement to WT in particular left as an exercise to the reader. :)

**Comment by michaelcahill** [comment]
First up, I just opened this issue as a placeholder so the thought didn't get lost.  I wasn't suggesting it as a near-term, high priority issue.

Next, I expected this to default on, syncing the directory as we do now.  I'd just like to provide the option to turn it off if a user knows their filesystem doesn't require it, or they don't require that level of durability (like we do with `checkpoint_sync=false`).

@bdlucas1 makes a good point: the database directory is not sufficient: we have to sync any directory containing a data file when that file is created or renamed.  Tables can be in a subdirectory of the database home.  I suspect running MongoDB with `--directoryPerDB` is not doing sufficient directory flushes today on filesystems that do require it.  (Fortunately, the most common filesystems on modern Linux systems don't).

We could have a reference-counted directory handle for every tree, I guess, but avoiding unnecessary flushes would require some additional tracking?

Michael.
