### ISSUE TITLE
wtstats graphing display issue

### ISSUE THREAD

**Issue by agorrod** [wiredtiger/wiredtiger#1884]
I've noticed that the wtstats.py script generates html, where the scroll seems to think it's longer than it is.

The left hand panel which shows the categories, if it doesn't fit all of the content in without a scroll bar. The last item (usually "Transaction") isn't visible. I've attached a screenshot that might help explain - there should be a "Transaction" box in the bottom left, but I can't scroll down that far.

Reproduces on my Mac in both Chrome and Safari.

![screen shot 2015-04-14 at 2 27 42 pm](https://cloud.githubusercontent.com/assets/1930121/7130375/c3ca433a-e2b2-11e4-8d97-e5415644ffab.png)

**Comment by rueckstiess** [comment]
Probably an issue with the CSS for `#sidebar-wrapper`

https://github.com/wiredtiger/wiredtiger/blob/develop/tools/wtstats/template/app/less/index.less#L73

It's defined as 100%, looks like it assumes 100% of the page instead of the parent container. 

Changing it to 90% works but not a clean solution as 90% of a small window might still not be enough for the entire sidebar to show. Need to figure out how to do this relative to parent container, or with an absolute offset (equal to menu bar height).
