### ISSUE TITLE
ubuntu 14.04 install fail

### ISSUE THREAD

**Issue by zhouhoo** [wiredtiger/wiredtiger#3180]
My system is ubuntu14.04, installed required software like autoconf,automake,libtool  as mentioned. python  is ok.  configure option is  --enable-python  .  but make step go into error:

```
(cd ../../lang/python && \
	     -python -threads -O -Wall -nodefaultctor -nodefaultdtor -I/home/june/temp/wiredtiger-master wiredtiger.i && \
	    mv wiredtiger.py wiredtiger/__init__.py)
/bin/bash: 行 1: -python: command not found.
make[1]: *** [../../lang/python/wiredtiger_wrap.c] error 127
```

**Comment by sulabhM** [comment]
@zhouhoo We no longer use the GitHub issue tracker. I'd recommend creating a WiredTiger JIRA ticket in the future. The reported issue has been fixed in the latest release, the associated ticket is at https://jira.mongodb.org/browse/WT-2688. You are missing "swig" package, which is required if you compile WiredTiger with python-enabled. "apt-get install swig" should resolve your issue.

**Comment by zhouhoo** [comment]
thank you for your help.
