### ISSUE TITLE
WiredTiger v2.9.2 tag

### ISSUE THREAD

**Issue by halex2005** [wiredtiger/wiredtiger#3447]
Is it correct that v2.9.2 tag is set after mongodb-branch (hash 05e73e771c2a75f22187d57017bd656e1571b329), not after master-branch (hash 4cccd81f4f38ae90ac16ab830c451470b207d94c)?

**Comment by halex2005** [comment]
And why #3393 changes doesn't come in v2.9.2 release?
I'm very confused with that release. What the status?

**Comment by agorrod** [comment]
@halex2005 the tag points to the latest change that was included in the release. If you checkout the tag, you will see the content of the release package, except for a small doc change https://github.com/wiredtiger/wiredtiger/commit/47b0813a658df20305213e639ea0f1abade3bfc2

In the future I'll create tags on the master branch to avoid confusion.

The 2.9.2 release was cut based on the content of a branch other than develop, since that was a known stable point.

Our next release will include the changes for [WT-3288](https://jira.mongodb.org/browse/WT-3288). If you are curious about which release a change is included in, you can look in the MongoDB JIRA bug tracking at the Fix Version field - it will reference the WiredTiger release that contains a fix or the next name in the sequence, if it's not in a released version of the project at the moment.
